// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC2-6HUZT1H0sAq3Hz20GxUOu1XfwJDXqE',
    appId: '1:986991921661:web:20fb8b65c0f84f53c0f194',
    messagingSenderId: '986991921661',
    projectId: 'ai-mental-75482',
    authDomain: 'ai-mental-75482.firebaseapp.com',
    storageBucket: 'ai-mental-75482.firebasestorage.app',
    measurementId: 'G-7XFEBKVVT0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBC9xv7rAPY6z8ZxRH0H0DroOth96p9O1U',
    appId: '1:986991921661:android:ada0a3284e713897c0f194',
    messagingSenderId: '986991921661',
    projectId: 'ai-mental-75482',
    storageBucket: 'ai-mental-75482.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBxc6Tsmvm3zlpmANbcLuLEPivtSNEHIIA',
    appId: '1:986991921661:ios:29a8f37f4677f3f7c0f194',
    messagingSenderId: '986991921661',
    projectId: 'ai-mental-75482',
    storageBucket: 'ai-mental-75482.firebasestorage.app',
    iosBundleId: 'com.example.aiHealth',
  );
}
